# Generated by Django 5.0.6 on 2024-06-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.PositiveIntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('emai', models.EmailField(blank=True, max_length=254)),
                ('body', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
